run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - typecheck
    - unused

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: sens.ai-backend
